/*
  File autogenerated by gengetopt version 2.12.2
  generated with the following command:
  gengetopt -i cmdline.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->host_given = 0 ;
  args_info->port_given = 0 ;
  args_info->url_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->host_arg = gengetopt_strdup ("localhost");
  args_info->port_arg = NULL;
  args_info->url_arg = NULL;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
  "Usage: %s [OPTIONS]...\n", CMDLINE_PARSER_PACKAGE);
  printf("\n");
  printf("%s\n","  -h, --help         Print help and exit");
  printf("%s\n","  -V, --version      Print version and exit");
  printf("%s\n","  -H, --host=STRING  Om engine host  (default=`localhost')");
  printf("%s\n","  -p, --port=STRING  Om engine port (must be specified if host is given)");
  printf("%s\n","  -u, --url=STRING   Om engine URL (can not be specified if host/port is given)");
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  if (args_info->host_arg)
    {
      free (args_info->host_arg); /* free previous argument */
      args_info->host_arg = 0;
    }
  if (args_info->port_arg)
    {
      free (args_info->port_arg); /* free previous argument */
      args_info->port_arg = 0;
    }
  if (args_info->url_arg)
    {
      free (args_info->url_arg); /* free previous argument */
      args_info->url_arg = 0;
    }
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "host",	1, NULL, 'H' },
        { "port",	1, NULL, 'p' },
        { "url",	1, NULL, 'u' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVH:p:u:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 'H':	/* Om engine host.  */
          if (local_args_info.host_given)
            {
              fprintf (stderr, "%s: `--host' (`-H') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->host_given && ! override)
            continue;
          local_args_info.host_given = 1;
          args_info->host_given = 1;
          if (args_info->host_arg)
            free (args_info->host_arg); /* free previous string */
          args_info->host_arg = gengetopt_strdup (optarg);
          break;

        case 'p':	/* Om engine port (must be specified if host is given).  */
          if (local_args_info.port_given)
            {
              fprintf (stderr, "%s: `--port' (`-p') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->port_given && ! override)
            continue;
          local_args_info.port_given = 1;
          args_info->port_given = 1;
          if (args_info->port_arg)
            free (args_info->port_arg); /* free previous string */
          args_info->port_arg = gengetopt_strdup (optarg);
          break;

        case 'u':	/* Om engine URL (can not be specified if host/port is given).  */
          if (local_args_info.url_given)
            {
              fprintf (stderr, "%s: `--url' (`-u') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->url_given && ! override)
            continue;
          local_args_info.url_given = 1;
          args_info->url_given = 1;
          if (args_info->url_arg)
            free (args_info->url_arg); /* free previous string */
          args_info->url_arg = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
    }

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  return (EXIT_FAILURE);
}
